spring.application.name=gateway-server
server.port=8079

spring.profiles.active=dev

spring.config.import=configserver:http://localhost:8089

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

#spring.main.web-application-type=reactive

spring.cloud.gateway.routes[0].id=explore
spring.cloud.gateway.routes[0].uri=http://localhost:9090
spring.cloud.gateway.routes[0].predicates[0]=Path=/explore/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=user_mgmt
spring.cloud.gateway.routes[1].uri=http://localhost:9091
spring.cloud.gateway.routes[1].predicates[0]=Path=/user_mgmt/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1