spring.application.name=kc-security
server.port=8096

spring.profiles.active=dev

spring.config.import=configserver:http://localhost:8089

keycloak.realm = backend
keycloak.auth-server-url = http://localhost:8080
keycloak.ssl-required = external
keycloak.resource = backend
keycloak.public-client = false
keycloak.credentials.secret = YOUR_CLIENT_SECRET  # From Keycloak client settings